INSERT INTO BOOKING (ID, EMAIL, FULL_NAME, ARRIVAL_DATE, DEPARTURE_DATE) VALUES (-1, 'nobody@mail.com', 'nobody', '1970-01-01', '2020-12-31');

--INSERT INTO Calendar(day, booking_Id) VALUES (CURDATE() + INTERVAL 1 DAY, -1);
